### ISSUE TITLE
Make 'Open link in new tab' work for blog entry links

### ISSUE THREAD

**Issue by pranavrajpal** [BianLee/opensourcecollage.com#10]
On Chrome, going to the home page and right clicking on any of the blog entries doesn't show the options usually displayed for links. That makes opening one of the blog posts in a new tab or window somewhat annoying.

This is what the menu should look like (the entries in Opportunities handle this correctly):
![image](https://user-images.githubusercontent.com/78008260/137186779-4a9e71dd-894c-41ec-858f-167db050f16b.png)

But this is what it looks like right now:
![image](https://user-images.githubusercontent.com/78008260/137186994-a837df81-b152-4761-a4da-18ed4b8e54c4.png)

I'm guessing this is happening because the `a` tags for the blog post entries don't have an `href` attribute.

**Comment by BianLee** [comment]
Fixed this issue. You were right about the fact that the it didn't have `href` attribute, and instead it was using an `onClick()` function. I changed `div` element to `Link` instead, and used `to` attribute, which is the pretty much the equivalent of `a` with `href` on JSX (instead of HTML).

**Comment by BianLee** [comment]
It is now working, so I'll close this issue.
